version: "3.9"

services:
  cucukakek-single:
    image: fahrizalfarid/cucu-kakek
    container_name: cucukakek-0
    command:
      - "--http=:1081"
      - "-a=1@127.0.0.1:8081"
      - "--join=-1"
      - "--secret-key=sEcr3t"
    ports:
      - 1081:1081
      - 8081:8081
    volumes:
      - ${HOME}/cucukakek:/data
    restart: always